### ISSUE TITLE
What is the effect of the code ?

### ISSUE THREAD

**Issue by xiaochunrilihe** [ConstellationBJUT/Coursera-DL-Study-Notes#2]
https://github.com/ConstellationBJUT/Coursera-DL-Study-Notes/blob/947387c4a7cc99d62b708bd2edb4a2a8e391a9ca/class5_week1_sequence/lstm/lstm_dinosaurus_name.py#L73

why do you choose 'idx' from vector 'y' randomly?
问什么要随机选择y中的索引下标，是为了随机生成名字吗？为什么不可以直接取y中的最大值？
或者直接使用训练好的模型生成名字？

**Comment by bjjoy** [comment]
> https://github.com/ConstellationBJUT/Coursera-DL-Study-Notes/blob/947387c4a7cc99d62b708bd2edb4a2a8e391a9ca/class5_week1_sequence/lstm/lstm_dinosaurus_name.py#L73
> 
> why do you choose 'idx' from vector 'y' randomly?
> 问什么要随机选择y中的索引下标，是为了随机生成名字吗？为什么不可以直接取y中的最大值？
> 或者直接使用训练好的模型生成名字？

explain: Sample the index of a character within the vocabulary from the probability distribution y
idx = np.random.choice(range(vocab_size), p=y.ravel())
不是随机，y是训练后通过模型获得的各个字符的概率，是根据所有字符的概率，随机获取一个。按照你所说的直接取最大概率也没有啥问题。这个例子不能直接生成名字，只能根据前几个字符生成下一个字符，直到结束符才算拼了一个名字。
